worker_processes: 1;
events {

}

http {
    server {
        listen 80;
        server_name 84.54.59.80;

        location /redirect-api/ {
            proxy_pass http://redirect_service:8000/;
        }

        location /user-api/ {
            proxy_pass http://user_service:8000/;
        }

        location /statistic-api/ {
            proxy_pass http://statistic_service:8000/;
        }

        location /link-api/ {
            proxy_pass http://link_service:8000/;
        }
    }
}